### PR TITLE
Trial project review

### PR DESCRIPTION
**Pull request by mntedev**
I did the following change to my trial project

1.   replace main div tag with main tag
2. add header semantic tag for header h1 element
3. replace div with section tag for each section
4. add figure and figcaption tag for img
5. use flexbox for ul element

### CODE REVIEW

**Review by youmari — CHANGES_REQUESTED** [review]
Hi @worashf, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that

- [ ] you haven't reviewed, please make sure to write at least two comments review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Danieldotcomcoder — COMMENTED** [review]
Hi @worashf , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't contain at least 2 review comments

As the previous reviewer mentioned,  for this task you need to make a review and add at least two comments 😃✔

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by koomekevo — COMMENTED** [review]
# Status: Invalid :x: :x: 
Hi @worashf, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly review your project with at least two comments as asked by the previous reviewers. To do a review click on _File changed_ tab and start your review. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mntedev** [comment]
I did the following activities

1. replace main div tag with main semantic tag
2. add header semantic tag
3. remove div tag and add section tag
4. add figure and figcaption tag for img

**Pull request closed without merging**
